# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADETDZ.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from openpyxl import *
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(243, 133)
        #MainWindow.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Bu Alana iconun dosya konumu eklenmeli"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 10, 75, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OTO ADET"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "KAÇ KALEM ?"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "KAÇINCI KALEM ?"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "DOSYA YOLU"))
        self.pushButton.setText(_translate("MainWindow", "ADET\n""GİR"))
        self.pushButton.setStyleSheet("background-color:LightGreen; border: 1px solid black ; border-radius:6px")
        self.pushButton.clicked.connect(self.adet)
        
    def adet(self):
        from python_imagesearch import imagesearch
        import keyboard
        import pyautogui as pag
        import time
        import os
        import sys
        import datetime
        an = datetime.datetime.now()
        anyil = str(an)[0:4]
        print(anyil)
        
        if anyil == "2023":
            parcakalem = (self.lineEdit.text())
            kacinci = (self.lineEdit_2.text())
            yol = (self.lineEdit_3.text())
            
            print(parcakalem, " ", kacinci, " ", yol)
            dongu1 = 0
            dongu2 = 0
            dongu3 = 0
            if parcakalem == "":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                aa = "'KAÇ KALEM ?' kısmına, aktarmak istediğin parçanın kalem miktarını girmelisin."
                msg.setText(aa)
                msg.setWindowTitle("Boş bıraktın")
                retval = msg.exec_()
                
            elif kacinci == "":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                aa = "'KAÇINCI KALEM ?' kısmına, aktarmak istediğin parçanların kaçıncı sıradan başlamasını istediğini girmelisin."
                msg.setText(aa)
                msg.setWindowTitle("Boş bıraktın")
                retval = msg.exec_()
    
            elif yol == "":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                aa = "'DOSYA YOLU' kısmına, aktarmak istediğin parçaların 'OTOADET' adlı excelinin bulunduğu dosya yolunu girmelisin."
                msg.setText(aa)
                msg.setWindowTitle("Boş bıraktın")
                retval = msg.exec_()
                
            elif parcakalem != "":
                if kacinci != "":
                    if yol != "":
                        parcakalem = int(parcakalem)
                        kacinci = int(kacinci)
                        toplam = (parcakalem - kacinci) - 1
                        MainWindow.hide()
                        
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Information)
                        aa = "Versiyon 8.0.2. Sürümünü kullanıyorsunuz \nLütfen program sırasında Klavye veya Mouse'a temas etmeyin.\n-AVB Software"
                        msg.setText(aa)
                        msg.setWindowTitle("İstek")
                        retval = msg.exec_()
                        
                        excelyol =  yol + r"\OTOADET.xlsx"
                        setup=load_workbook(excelyol)
                        setup1=setup.active
                        print(excelyol)
                        while dongu1 < 30:
			# Bu alan gizlilik anlaşması nedeniyle paylaşılamamaktadır
                        while kacinci <= parcakalem:
                            SAYSTR = str(kacinci)
                            print(SAYSTR)
                            kod= setup1["A" + SAYSTR].value
                            adet= setup1["B" + SAYSTR].value
                            
                            kacinci = kacinci + 1
                            
                            print(kod , adet)
                            while dongu2<30:
                                # Bu alan gizlilik anlaşması nedeniyle paylaşılamamaktadır
                                if dongu2>=30 :      
                                    msg = QMessageBox()
                                    msg.setIcon(QMessageBox.Information)
                                    aa = kod + "adında bir parça bulunamadı. Program sonlandığında manuel ekleyiniz"
                                    msg.setText(aa)
                                    msg.setWindowTitle("Dft bulunamadı")
                                    retval = msg.exec_()
                                    break
                            while dongu3<30:
                                # Bu alan gizlilik anlaşması nedeniyle paylaşılamamaktadır
                                    
                                elif DIAX == -1:
                                    dongu3 = dongu3 +1
                                    
                                if dongu3>=30 :      
                                    msg = QMessageBox()
                                    msg.setIcon(QMessageBox.Information)
                                    aa = kod + "adında bir parça bulunamadı. Program sonlandığında manuel ekleyiniz"
                                    msg.setText(aa)
                                    msg.setWindowTitle("Dft bulunamadı")
                                    retval = msg.exec_()
                                    break
                                    
                                    
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Information)
                        girilen = str(girilen)
                        aa = girilen + " kalem parçanın adedi girildi.\n-AVB Software"
                        msg.setText(aa)
                        msg.setWindowTitle("Bitti")
                        retval = msg.exec_()
                        MainWindow.close()
                        
        if anyil != "2023":
            MainWindow.close()
                    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
